name: Release

on:
  workflow_run:
    workflows: [ 'Quality gate' ]
    branches: [ main ]
    types:
      - completed

jobs:
  release:
    name: Create a new release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm ci

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.SR_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.SR_NPM_TOKEN }}
        run: npx semantic-release
